services:
    snowio_published_connector.provider.form.job_instance:
        class: '%pim_enrich.provider.form.job_instance.class%'
        arguments:
            -
                snowio_complete_export: snowio-csv-published-product-export
        tags:
            - { name: pim_enrich.provider.form, priority: 100 }
